import { useAuth } from '@/context/AuthContext';

const adminTheme = {
    // Sidebar
    logoBg: 'bg-purple-50',
    activeBg: 'bg-purple-50',
    activeText: 'text-purple-700',
    activeIcon: 'text-purple-600',
    installBg: 'bg-purple-600',
    installHover: 'hover:bg-purple-700',
    // Header
    titleText: 'text-purple-600',
    titleHover: 'hover:text-purple-700',
    // Dashboard gradient
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-purple-700',
    gradientSubtext: 'text-purple-100',
    // Spinner
    spinnerBorder: 'border-purple-600/20',
    spinnerTop: 'border-t-purple-600',
    // Action card hover
    actionHover: 'group-hover:text-purple-600',
    // UserDropdown gradient
    avatarFrom: '#9333ea',
    avatarTo: '#7e22ce',
    // Profile pill
    pillBg: 'bg-purple-100',
    pillText: 'text-purple-700',
    // Language selector
    selectedBg: 'bg-purple-50',
    selectedText: 'text-purple-700',
    borderLight: 'border-purple-100',
    // Dropdown hover
    hoverBg: 'hover:bg-purple-50',
    hoverText: 'hover:text-purple-600',
    groupHoverIcon: 'group-hover:text-purple-600',
    // General UI
    btnPrimary: 'bg-purple-600',
    btnPrimaryHover: 'hover:bg-purple-700',
    btnDisabled: 'bg-purple-400',
    focusRing: 'focus:ring-purple-200 focus:border-purple-400',
    softHover: 'hover:bg-purple-100',
    accent: 'text-purple-600',
    accentHover: 'hover:text-purple-700',
    accentBgHover: 'hover:bg-purple-50',
    accentBg: 'bg-purple-50',
    accentText: 'text-purple-700',
    checkboxBg: 'bg-purple-600 border-purple-600',
    badgeBg: 'bg-purple-600',
    softBgHalf: 'bg-purple-50/30',
    hoverSoftBgHalf: 'hover:bg-purple-50/30',
};

const studentTheme = {
    logoBg: 'bg-emerald-50',
    activeBg: 'bg-emerald-50',
    activeText: 'text-emerald-700',
    activeIcon: 'text-emerald-600',
    installBg: 'bg-emerald-600',
    installHover: 'hover:bg-emerald-700',
    titleText: 'text-emerald-600',
    titleHover: 'hover:text-emerald-700',
    gradientFrom: 'from-emerald-600',
    gradientTo: 'to-emerald-700',
    gradientSubtext: 'text-emerald-100',
    spinnerBorder: 'border-emerald-600/20',
    spinnerTop: 'border-t-emerald-600',
    actionHover: 'group-hover:text-emerald-600',
    avatarFrom: '#059669',
    avatarTo: '#047857',
    pillBg: 'bg-emerald-100',
    pillText: 'text-emerald-700',
    selectedBg: 'bg-emerald-50',
    selectedText: 'text-emerald-700',
    borderLight: 'border-emerald-100',
    hoverBg: 'hover:bg-emerald-50',
    hoverText: 'hover:text-emerald-600',
    groupHoverIcon: 'group-hover:text-emerald-600',
    btnPrimary: 'bg-emerald-600',
    btnPrimaryHover: 'hover:bg-emerald-700',
    btnDisabled: 'bg-emerald-400',
    focusRing: 'focus:ring-emerald-200 focus:border-emerald-400',
    softHover: 'hover:bg-emerald-100',
    accent: 'text-emerald-600',
    accentHover: 'hover:text-emerald-700',
    accentBgHover: 'hover:bg-emerald-50',
    accentBg: 'bg-emerald-50',
    accentText: 'text-emerald-700',
    checkboxBg: 'bg-emerald-600 border-emerald-600',
    badgeBg: 'bg-emerald-600',
    softBgHalf: 'bg-emerald-50/30',
    hoverSoftBgHalf: 'hover:bg-emerald-50/30',
};

const teacherTheme = {
    logoBg: 'bg-blue-50',
    activeBg: 'bg-blue-50',
    activeText: 'text-blue-700',
    activeIcon: 'text-blue-600',
    installBg: 'bg-blue-600',
    installHover: 'hover:bg-blue-700',
    titleText: 'text-blue-600',
    titleHover: 'hover:text-blue-700',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-blue-700',
    gradientSubtext: 'text-blue-100',
    spinnerBorder: 'border-blue-600/20',
    spinnerTop: 'border-t-blue-600',
    actionHover: 'group-hover:text-blue-600',
    avatarFrom: '#3b82f6',
    avatarTo: '#1d4ed8',
    pillBg: 'bg-blue-100',
    pillText: 'text-blue-700',
    selectedBg: 'bg-blue-50',
    selectedText: 'text-blue-700',
    borderLight: 'border-blue-100',
    hoverBg: 'hover:bg-blue-50',
    hoverText: 'hover:text-blue-600',
    groupHoverIcon: 'group-hover:text-blue-600',
    btnPrimary: 'bg-blue-600',
    btnPrimaryHover: 'hover:bg-blue-700',
    btnDisabled: 'bg-blue-400',
    focusRing: 'focus:ring-blue-200 focus:border-blue-400',
    softHover: 'hover:bg-blue-100',
    accent: 'text-blue-600',
    accentHover: 'hover:text-blue-700',
    accentBgHover: 'hover:bg-blue-50',
    accentBg: 'bg-blue-50',
    accentText: 'text-blue-700',
    checkboxBg: 'bg-blue-600 border-blue-600',
    badgeBg: 'bg-blue-600',
    softBgHalf: 'bg-blue-50/30',
    hoverSoftBgHalf: 'hover:bg-blue-50/30',
};

// Default & Lector: light gray
const defaultTheme = {
    logoBg: 'bg-gray-50',
    activeBg: 'bg-gray-50',
    activeText: 'text-gray-600',
    activeIcon: 'text-gray-500',
    installBg: 'bg-gray-500',
    installHover: 'hover:bg-gray-600',
    titleText: 'text-gray-500',
    titleHover: 'hover:text-gray-600',
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-gray-600',
    gradientSubtext: 'text-gray-200',
    spinnerBorder: 'border-gray-400/20',
    spinnerTop: 'border-t-gray-400',
    actionHover: 'group-hover:text-gray-500',
    avatarFrom: '#6b7280',
    avatarTo: '#4b5563',
    pillBg: 'bg-gray-50',
    pillText: 'text-gray-600',
    selectedBg: 'bg-gray-50',
    selectedText: 'text-gray-600',
    borderLight: 'border-gray-100',
    hoverBg: 'hover:bg-gray-50',
    hoverText: 'hover:text-gray-600',
    groupHoverIcon: 'group-hover:text-gray-500',
    btnPrimary: 'bg-gray-500',
    btnPrimaryHover: 'hover:bg-gray-600',
    btnDisabled: 'bg-gray-300',
    focusRing: 'focus:ring-gray-200 focus:border-gray-400',
    softHover: 'hover:bg-gray-100',
    accent: 'text-gray-500',
    accentHover: 'hover:text-gray-600',
    accentBgHover: 'hover:bg-gray-50',
    accentBg: 'bg-gray-50',
    accentText: 'text-gray-600',
    checkboxBg: 'bg-gray-500 border-gray-500',
    badgeBg: 'bg-gray-500',
    softBgHalf: 'bg-gray-50/30',
    hoverSoftBgHalf: 'hover:bg-gray-50/30',
};

export type RoleTheme = typeof adminTheme;

export function useRoleTheme(): RoleTheme {
    const { user } = useAuth();
    const roleName = (user?.role?.name || '').toLowerCase();

    if (roleName.includes('admin')) return adminTheme;
    if (roleName.includes('student')) return studentTheme;
    if (roleName.includes('professor') || roleName.includes('coordinator')) return teacherTheme;
    return defaultTheme;
}
